name: CI/CD Workflow for our Class

on: 
  push:
    branches: olt

jobs:
  build: 
    name: Build Frontend Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Ensure Node Version
        uses: actions/setup-node@v4
        with: 
          node-version: 16.x
      
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: fe-node-${{ hashFiles('frontend/package-lock.json') }}

      - name: Install deps
        run: cd frontend && npm i

      - name: Compile code
        run: cd frontend && npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with: 
          path: frontend/build

  security-audit: 
    name: Audit Deps
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: ensure node installed and right version
        uses: actions/setup-node@v4
        with: 
          node-version: 16.x

      - name: audit
        run: cd frontend && npm audit --omit=dev 
  
  lint:
    name: 🧼 Ensure Code Style
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 16
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: fe-node-${{ hashFiles('frontend/package-lock.json') }}

      - name: Install deps
        run: cd frontend && npm i

      - name: 😂 Lint code
        run: cd frontend && npm run lint
  
  test:
    name: 🧪 Run Unit Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 16
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: fe-node-${{ hashFiles('frontend/package-lock.json') }}

      - name: Install deps
        run: cd frontend && npm i

      - name: Run the unit tests
        run: cd frontend && npm run test-ci